### ISSUE TITLE
Incompatible Fast Ram Type

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [AmiDARK/Amos-Professional-AGA-Releases#5] opened 2020-09-30 16:53 UTC
Hi

Just to let you know the program doesnt load /run when 'fast ram' is set in FS-UAE. I think this would be Z2 ram. It gets stuck on a grey screen.

This was using the default A1200 setting and adding any amount of fastram. I've also used the latest update from the repo.

I had to switch to using an A4000 (040+) because this would allow me to select Z3 ram, and then it loaded.

This is probably worth checking :)

Thanks

**Comment by AmiDARK** [comment] 2020-09-30 18:25
Hello,

Did you try original AMOS Professional 2.0 with the same configuration ?
I ask you about this, because I changed nothing concerning memory allocation AMOS Professional do .
From what I've seen, it uses PUBLIC+CLEAR to allocate memory. I'll recheck.
Maybe that with the setup defined llike you said, fastram is not considered as PUBLIC fastram ram ?
With WinUAE, I tried some memory configuration Z2, Z3, etc. without having issues...
Can you send me the details of you FS-UAE configuration so I will try to test this emulator with Amos Professional AGA.

**Comment by HoraceAndTheSpider** [comment] 2020-09-30 19:38
Hi

Yes, this was the same mini-boot setup j had previously used with old AMOS. In fact, it was the same amiga setup i used for a very early version of AMOS AGA/X - before all the stuff early in the year!  At that point it was certainly working. 

I will create an fs-uae Config for it for you , but it is pretty much the QuickStart-Config setting for A1200, with fastram added and a hard drive for booting direct into AMOS.

**Comment by HoraceAndTheSpider** [comment] 2020-10-07 21:24
I could have sworn I replied to this with the file attached... I will get it again tomorrow .

However I have the same problem with uae4all2 which sadly only has the z2 fastram option and so I am having to select extra  chipram but then I am constantly experiencing a crash when I try to do anything (ie clicking the right mouse button)
![image](https://user-images.githubusercontent.com/567602/95389157-50bf8e80-08eb-11eb-8faf-b02e59de7dbb.jpg) 

Will be a shame if I am not able to find a way to run it on a portable device! I am not finding much time to try it out on my laptop and was hoping this might help.

**Comment by HoraceAndTheSpider** [comment] 2020-10-11 20:16
[Archive.zip](https://github.com/AmiDARK/Amos-Professional-AGA-Releases/files/5361924/Archive.zip)

Fs-uae config files as promised!

**Comment by AmiDARK** [comment] 2020-10-12 06:36
Hello,
Thank you,
I will install FS-UAE on my configuration and test your files.
I'll check if I have other flags I can use to allocate memory to makes Amos Pro works with  (exec/memory.i)
Regards,

Frederic Cordier Aka AmiDARK

**Comment by HoraceAndTheSpider** [comment] 2020-12-13 22:10
just wondering if this was fixed - i was going to try porting one of my old projects to AGA :)

**Comment by HoraceAndTheSpider** [comment] 2020-12-13 22:15
as a further to this, when i tried to use "get disc fonts" with the Z3 ram work-around i got an "out of memory" error 

I dont use disc fonts often, but one of my old projects had it

**Comment by AmiDARK** [comment] 2020-12-13 22:41
Hello HoraceAndTheSpider.

I was not able to makes fs-uae works on my Windows configuration to reproduce your issue ( Z3 Fast Memory was not detected by the Workbench with my Amiga OS 3.9 setup... And I wasn't able to configure to make the memory being detected ... :( ) 
And with WinUAE using Z3 Fast Ram, Amos Professional classics & AGA Versions works correctly ..

We must find a solution to makes me being able to reproduce your issue in order to fix it...
Contact me using the contact form in the amos pro aga website : http://amos-professional-aga.frederic-cordier.fr/?contact
I'll answer you from my email so you can send me files to help me reproduce the bug (I don't remind if you did send me files or not, and did not find them :(

**Comment by AmiDARK** [comment] 2020-12-14 17:17
Hello HoraceAndTheSpider,

As seen with you, this issue is linked to the way FS-UAE setup Amiga configurations.
When using A1200 config, If you don't manually specify "Rom 3.1 68020", FS-UAE will not create a full Amiga 1200 compatible configuration. if you specify "Rom 3.1 68020", then the issues are gone ...

I close this issue as the new Amos Professional Unity will fix this kind of problems with the configuration-detection-setup I'll add for ECS/OCS / AGA / SAGA chipsets.

**Closed by AmiDARK** 2020-12-14 17:17 UTC
